[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rbc25_demo"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = "==3.12.8"
license = "MIT"
keywords = []
authors = [
  { name = "klaasderks", email = "61226892+kad-derksn@users.noreply.github.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["robotframework==7.2.2", "robotframework-browser"]

[project.urls]
Documentation = "https://github.com/klaasderks/rbc25-demo#readme"
Issues = "https://github.com/klaasderks/rbc25-demo/issues"
Source = "https://github.com/klaasderks/rbc25-demo"

[tool.hatch.version]
path = "src/rbc25_demo/__about__.py"

[tool.hatch.envs.default]
dependencies = ["robotframework-tidy", "robotframework-robocop"]
post-install-commands=[
  "rfbrowser init"
  ]


[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/rbc25_demo tests}"

[tool.coverage.run]
source_pkgs = ["rbc25_demo", "tests"]
branch = true
parallel = true
omit = [
  "src/rbc25_demo/__about__.py",
]

[tool.coverage.paths]
rbc25_demo = ["src/rbc25_demo", "*/rbc25-demo/src/rbc25_demo"]
tests = ["tests", "*/rbc25-demo/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
